### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by chovy** [chiefy/node-hockey-helper#2]
I am curious how the path works? You have some non-existent path hard coded.

also, why does it sometimes ask for sudo and othertimes not? Why is it needed?

**Comment by chiefy** [comment]
@chovy not sure what you mean? I see a path hard-coded into `_findVLCPath`, but that stuff isn't actually hooked up yet. I was just using it to test, but never took it out. That is actually for the VLC launching stuff, which I haven't gotten around to. Maybe I will now that it's almost playoff time!

As for sudo: FuckNeulion requires sudo because it runs a webserver that binds to a local tcp port. This is a limitation of FuckNeulion, and since they have not open-sourced their code, I can't do anything about it. I am using the [sudo npm package](https://www.npmjs.com/package/sudo) which will cache your password when entered. You can check the code, but I am not doing anything nasty with it - just launching `sudo java -jar FuckNeulion.jar <args>`

**Comment by chovy** [comment]
I figured as much about the sudo. I didn't notice the `_findVLCPath` was not being used. So that makes sense.

Just curious, its a cool project. One annoyance I have though is the infinite cycling when selecting a game. I don't know if its possible to disable that feature.

**Comment by chiefy** [comment]
@chovy, I agree - the infinite cycling is annoying. I am using [inquirer](https://github.com/SBoudrias/Inquirer.js/) for the CLI stuff, and I think that's how it works by default.

Yeah, I agree re: blowing away prototype. In this case, this was something I wrote over a weekend, so it was mostly quick and dirty. Since `Hockey` is really just a singleton, I don't even really need to use the prototype for method definition.

Thanks again for the feedback! I might try to improve it during the playoffs.

**Comment by chovy** [comment]
I'm working on a version for NFL, based on what you've done here.

**Comment by chiefy** [comment]
@chovy that's awesome, does the NFL also use Neulion? Wasn't aware of a similar thing - will have to check /r/nflstreams when the time is right.
